version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    extra_hosts: 
      - "dockerhost:10.0.75.1"
  kafka:
    build: .
    ports:
      - "9092:9092"
    extra_hosts: 
      - "dockerhost:10.0.75.1"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.21.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
