
version: '2'

services:

   mongo:
      build: .
      ports:
        - "27017:27017"
      volumes:
        - ./mongo:/data/db
      networks:
        - backend

### Networks Setup ############################################

networks:
  backend:
    external:
      name: backend