version: '2'

services:

   redis:
      build: .
      volumes:
        - ./data:/data
      ports:
        - "6379:6379"
      networks:
        - backend


networks:
  backend:
    external:
      name: backend